### ISSUE TITLE
a dep on version 1.2 of htdp-lib? version exception?

### ISSUE THREAD

**Issue by AlexKnauth** [lexi-lambda/racket-2htdp-typed#2]
Right now the pkg-build.racket-lang.org build fails because add-solid-curve isn't provided.  Would adding a dep on version 1.2 of htdp-lib help, or should there be a version exception that doesn't include add-solid-curve, or what?

**Comment by lexi-lambda** [comment]
I added a dependency on version 1.2, and I think that should resolve the problem once it gets rebuilt by `pkg-build`. If it doesn't, I'll reopen this issue.

**Comment by lexi-lambda** [comment]
I've added a version exception for 6.1.1.

**Comment by AlexKnauth** [comment]
The build on pkg-build.racket-lang.org is still failing

```
image.rkt:43:9: Type Checker: Type (-> Nonnegative-Real Mode (U Image-Color Pen) Image) could not be converted to a contract: contract generation not supported for this type
  in: (Nonnegative-Real Mode (U Pen Image-Color) -> Image)
```

I'm not sure, but I think it's because v6.1.1 can't generate a contract for `(Instance Bitmap%)`.

Would it make sense to just define Image as htdp:image, and force 6.1.1 users to use `(assert bm image?)` ?

Or I could be wrong and it might be something else that prevents it from being converted to a contract.

**Comment by lexi-lambda** [comment]
This is what I get for not actually testing my builds on v6.1.1. I've actually reinstalled 6.1.1 and I'll try and get it building on that version and submit a fix.

**Comment by lexi-lambda** [comment]
Okay, implemented the change you proposed. Builds on my machine running 6.1.1, hopefully we won't encounter any problems on pkg-build.
